export const QUERY_KEY = {
    USER: {
        GET_USERS_ONLINE: "GET_USERS_ONLINE",
        UPDATE_INFO_ME: "UPDATE_INFO_ME",
    },
    MATCH: {
        GET_MATCHES: "GET_MY_MATCHES",
    },
    TABLE: {
        GET_TABLES: "GET_TABLES",
    },
    FRIEND: {
        GET_FRIENDS: 'GET_FRIENDS',
        DELETE_FRIEND: 'DELETE_FRIEND',
        SEND_FRIEND_REQUEST: 'SEND_FRIEND_REQUEST',
        GET_SENT_FRIEND_REQUEST: 'GET_SENT_FRIEND_REQUEST',
        GET_RECEIVED_FRIEND_REQUEST: 'GET_RECEIVED_FRIEND_REQUEST',
        DELETE_SEND_FRIEND_REQUEST: 'DELETE_SEND_FRIEND_REQUEST',
        REPLY_RECEIVED_FRIEND_REQUEST: 'REPLY_RECEIVED_FRIEND_REQUEST'
    }
}